name: Test Weather Notifier Debug Mode

on:
  # Allow manual trigger from GitHub
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run in debug mode'
        required: false
        default: 'true'
  
  # You can keep these triggers or remove them if you only want manual execution
  push:
    branches:
      - main
    paths:
      - 'scripts/weather-notifier.js'
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/weather-notifier.js'

jobs:
  test-debug-mode:
    name: Test Weather Notifier in Debug Mode
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install openai firebase-admin dotenv
      
      - name: Find weather notifier script
        id: find-script
        run: |
          SCRIPT_PATH=$(find . -type f -name "weather-notifier.js" | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "Error: weather-notifier.js not found in repository"
            exit 1
          fi
          echo "script_path=$SCRIPT_PATH" >> $GITHUB_OUTPUT
      
      - name: Run weather notifier in debug mode
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DEBUG_MODE: 'true'  # Force debug mode to be true
        run: |
          # Create a temporary file with CommonJS import syntax
          TEMP_FILE=$(mktemp)
          cat ${{ steps.find-script.outputs.script_path }} | sed 's/import \* as admin from/const admin = require/g' | sed 's/import { OpenAI } from/const { OpenAI } = require/g' | sed 's/import dotenv from/const dotenv = require/g' > $TEMP_FILE
          echo "Running modified script..."
          node $TEMP_FILE
      
      - name: Report results
        if: always()
        run: |
          echo "Weather notifier debug test completed at $(date)"
          echo "See logs for details"